### PR TITLE
Updated getaway shootout

### PR DESCRIPTION
**Pull request by Pokeknight2610**
This is the most recent version, which includes time trials, 2 more maps, and many more characters. The version you have now does not have these.

### CODE REVIEW

**Comment by Pokeknight2610** [comment]
Hello?

**Comment by Pokeknight2610** [comment]
Ayo merge please?

**Comment by Mr-milky-way** [comment]
Please add the gtag; and don't reference other sites
`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RW5XLDCNXJ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'G-RW5XLDCNXJ');
</script>`

**Comment by Pokeknight2610** [comment]
1. Whats a gtag
2. It would take too long, you can fork it from here if you want github.com/pokeknight2610/getawayshootout

**Comment by Mr-milky-way** [comment]
Gtag = google analytics tag

**Pull request closed without merging**
